import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedCustomers() {
  const customers = [
  {
    name: "Cliente Prueba REA ",
    contact: "12312313",
    address: "",
    map_url: "Ubicacion",
    email: null,
    optionalEmail: null,
    company_name: null,
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-05 20:28:07"
  },
  {
    name: "CLIENTE NUEVO DESDE SECRETARIA ",
    contact: "123414124",
    address: "DIRECCION",
    map_url: "",
    email: null,
    optionalEmail: null,
    company_name: "RAZON",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-06 19:28:25"
  },
  {
    name: "QUIM.  MARICELA DE LA CRUZ ",
    contact: "5532313759",
    address: "AV TLAHUAC #1004, LOMAS ESTRELLA, IZTAPALAPA, CP09890",
    map_url: "",
    email: "compras@cimigen.org.mx",
    optionalEmail: "compras@cimigen.org.mx",
    company_name: "ASOCIACION HISPANO MEXICANA IAP",
    postalCode: "09890",
    rfc: "",
    status: "active",
    createdAt: "2023-06-06 19:55:08"
  },
  {
    name: "DISTRIBUIDORA CRIL ",
    contact: "4442791812",
    address: "SAN LUIS POTOSI, S.L.P.",
    map_url: "",
    email: "equipo_cril@hotmail.com",
    optionalEmail: "equipo_cril@hotmail.com",
    company_name: "ALDO LEMUS RANGEL",
    postalCode: "78399",
    rfc: "",
    status: "active",
    createdAt: "2023-06-08 03:16:15"
  },
  {
    name: "LIC. LILIAN GARCIA KALIS / CDI CUERNAVACA ",
    contact: "7772747901",
    address: "GUAYABOS #1 ESQUINA MONTEALBAN, COL. LAS PALMAS, CUERNAVACA, MORELOS CP62050",
    map_url: "https://goo.gl/maps/kbn9iafqprm8Nhhq7",
    email: "lilian_kalis@hotmail.com",
    optionalEmail: "lilian_kalis@hotmail.com",
    company_name: "CENTRO DE DIAGNOSTICO POR IMAGENES",
    postalCode: "62050",
    rfc: "CDI8203304T3",
    status: "active",
    createdAt: "2023-06-10 01:22:36"
  },
  {
    name: "DR ROBERTO GARCIA LOPEZ / HOSPITAL SANTA ANITA",
    contact: "9511174266",
    address: "GUILLERO PRIETO #201 COLONIA SANTA ANITA, OAXACA, CP68150",
    map_url: "https://goo.gl/maps/MjjG2NJjnaaHcZqu8",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-10 01:35:53"
  },
  {
    name: "DR NICOLAS LICEAGA ARZATE",
    contact: "7355429215",
    address: "GALEANA # 87C, CENTRO, AXOCHIAPAN, MORELOS",
    map_url: "https://goo.gl/maps/feebUmMvpUddjn319",
    email: "santafeaxochiapan@hotmail.com",
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-10 03:06:16"
  },
  {
    name: "LIC. LOURDES BERUMEN / HOSPITAL DE ESPECIALIDADES ",
    contact: "4949490443",
    address: "PASEO DEL VIEJO POZO S/N, JARDINES DE RAMON LOPEZ VELARDE, JEREZ , ZACATECAS, CP99390",
    map_url: "https://goo.gl/maps/LBTf2uBKYCkqwxKA8",
    email: "hospespjz@yahoo.com.mx",
    optionalEmail: "hospespjz@yahoo.com.mx",
    company_name: "HOSPITAL DE ESPECIALIDADES JEREZ",
    postalCode: "99390",
    rfc: "",
    status: "active",
    createdAt: "2023-06-10 03:27:30"
  },
  {
    name: "DR BENIGNO ALFONSO REYES FRAGOZO",
    contact: "2464690118",
    address: "AV. INDEPENDENCIA #60-B, CENTRO, TLAXCALA,",
    map_url: "https://goo.gl/maps/jJzZtC4kVjBpb2Rh7",
    email: "creidetlaxcala@prodigy.net.mx",
    optionalEmail: "creidetlaxcala@prodigy.net.mx",
    company_name: "CENTRO DE RADIOLOGIA E IMAGEN DE TLAXCALA",
    postalCode: "90000",
    rfc: "CRI9309234B3",
    status: "active",
    createdAt: "2023-06-12 17:34:03"
  },
  {
    name: "DRA LETICIA BARRERA CASTILLO",
    contact: "5519195029",
    address: "tlacotalpan #96, colonia roma",
    map_url: "https://maps.app.goo.gl/ajGgFkjBuGUN72Bj8",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-13 19:11:19"
  },
  {
    name: "DISTRIBUIDORA CRIL / ING ALDO LEMUS RANGEL",
    contact: "4442791812",
    address: "ALEJANDRINA #1237, VALLE DORADO, SAN LUIS POTOSI, S.L.P.",
    map_url: "",
    email: "equipo_cril@hotmail.com",
    optionalEmail: "equipo_cril@hotmail.com",
    company_name: "ALDO LEMUS RANGEL",
    postalCode: "78399",
    rfc: "LERA860105936",
    status: "active",
    createdAt: "2023-06-15 21:37:53"
  },
  {
    name: "DR. DANIEL SOTO ANAYA",
    contact: "7711292456",
    address: "Centro Médico San Ángel Miguel Hidalgo 25, Centro, 43480 Tenango de Doria, Hgo.",
    map_url: "https://goo.gl/maps/eWFXf9wQGjPgEyb86",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-17 22:40:55"
  },
  {
    name: "ING. DANIEL LEMUS BAÑUELOS",
    contact: "3311726935",
    address: "C. ANDRÉS TERÁN 319A, SANTA TERESITA, 44600, GUADALAJARA, JALISCO, MÉXICO",
    map_url: "",
    email: "electronica.audiomp319a@gmail.com",
    optionalEmail: null,
    company_name: ".GE",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-20 15:40:34"
  },
  {
    name: "IDSAMED.COM",
    contact: "5544799807",
    address: "",
    map_url: "",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-20 19:54:44"
  },
  {
    name: "DR CLAUDIO ENRIQUE ZAMORA VERGARA",
    contact: "7333361344",
    address: "IGUALA, GUERRERO",
    map_url: "IGUALA",
    email: "drclaudiozamora@hotmail.com",
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-20 22:29:12"
  },
  {
    name: "DR OSCAR ALEJANDRO SANCHEZ GÁMEZ",
    contact: "4622104678",
    address: "ISABEL 1848, FRACC. GÁMEZ , IRAPUATO, GTO., CP36650",
    map_url: "",
    email: "droscargamez@gmail.com",
    optionalEmail: null,
    company_name: "OSCAR ALEJANDRO SANCHEZ GÁMEZ",
    postalCode: "36650",
    rfc: "",
    status: "active",
    createdAt: "2023-06-21 12:48:05"
  },
  {
    name: "DR OSVALDO DURÁN JUAREZ",
    contact: "9631200104",
    address: "COMITÁN, CHIAPAS",
    map_url: "",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-26 16:21:55"
  },
  {
    name: "DR OSVALDO  DURAN JUÁREZ",
    contact: "9631200104",
    address: "11 calle sur ponniente #40, centro, comitan de dominguez",
    map_url: "https://goo.gl/maps/Hpozb47SJRcskrvHA",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-27 23:02:00"
  },
  {
    name: "QBP. JORGE ANTONIO ALFARO RUIZ",
    contact: "9631062597",
    address: "4a Calle Sur Ote #14,colonia centro, barrio jesusito, entre la I. Suriana y Granda, CP30000 Comitán de Domínguez, CHIAPAS",
    map_url: "https://goo.gl/maps/LM6yp9UBvfLMchUJ6",
    email: null,
    optionalEmail: null,
    company_name: "JORGE ANTONIO ALFARO RUIZ",
    postalCode: "30000",
    rfc: "AARJ620806QX6",
    status: "active",
    createdAt: "2023-06-28 17:04:31"
  },
  {
    name: "ING PEDRO ERNESTO ALVARADO TURRUBIATES",
    contact: "4442044902",
    address: "DHL SAN LUIS POTOSI (OCURRE)  Av Nereo Rodríguez Barragán 620-Letra C, Col del Valle, 78200 San Luis, S.L.P.",
    map_url: "   https://goo.gl/maps/REpgi6yUWgL9b8fT6",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-06-30 15:46:48"
  },
  {
    name: "DRA. MONICA ELIZABETH RUELAS ANZALDO",
    contact: "7772576886",
    address: "HERNAN CORTES #5, REFORMA , CUERNAVACA, MORELOS, CP62260",
    map_url: "https://goo.gl/maps/spmfEueDJ26Pua9T6",
    email: "recepcionginecologia301@gmail.com",
    optionalEmail: "recepcionginecologia301@gmail.com",
    company_name: "SOCIEDAD MEDICA RUELAS",
    postalCode: "62260",
    rfc: "",
    status: "active",
    createdAt: "2023-06-30 20:58:48"
  },
  {
    name: "DR VITO LUIS DEVIANA LUNA",
    contact: "9631138708",
    address: "Primera Calle Sur Pte. 45, Sacsalum, 30187 Las Margaritas, Chis.",
    map_url: "https://goo.gl/maps/gSR4ZH8eWDt6wYPR9",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-07-03 18:59:18"
  },
  {
    name: "DR VICTOR MANUEL VARGAS AGUILAR",
    contact: "5522488012",
    address: "Av Hidalgo 20, Fátima, 90300 Apizaco, Tlax.",
    map_url: "https://goo.gl/maps/kajBVTW95Six2CqGA",
    email: "v_vargas_aguilar@hotmail.com",
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-07-03 22:12:09"
  },
  {
    name: "DR JULIO ANTONIO GARCIA GOMEZ",
    contact: "9636320607",
    address: "2a  avenida oriente sur #95, comitan, chiapas",
    map_url: "",
    email: "julipau24@hotmail.com",
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-07-12 13:30:11"
  },
  {
    name: "MARGARITA  DE LA  LUZ  MANZANAREZ / UNILIVE ",
    contact: "2223224494",
    address: "Atlixcáyotl 1499-A, Edificio Valcob, Atlixcáyotl, Unidad territorial Atlixcayotl, 72820 Puebla,",
    map_url: "https://goo.gl/maps/NynQBy1Wbpp6HLhg6",
    email: "administracion@unilive.com.mx",
    optionalEmail: "administracion@unilive.com.mx",
    company_name: "UNIDAD EN FERTILIDAD Y ESTERILIDAD PUEBLA",
    postalCode: "72820",
    rfc: "",
    status: "active",
    createdAt: "2023-07-19 17:40:01"
  },
  {
    name: "DR. OCTAVIO HERRERA OSORIO ",
    contact: "2226755687",
    address: "Cto. Guadalupe Nte. 9, Alseseca, 72560 Puebla, Pue.",
    map_url: "https://goo.gl/maps/UeUi4GMjfo5uR9sA8",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-07-20 20:23:38"
  },
  {
    name: "DR CARLOS HERRERA  CABRERA ",
    contact: "2226755687",
    address: "Calle 24 Sur 4312, Alseseca, 72543 Puebla, Pue.",
    map_url: "https://goo.gl/maps/kTNcXK283Nqj8EzLA",
    email: null,
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-07-27 00:59:21"
  },
  {
    name: "ING ONESIMO ALEJANDRO REYES SOTO ",
    contact: "6671894270",
    address: "INFONAVIT LAS FLORES, CULIACAN SINALOA,CP80159",
    map_url: "",
    email: "Bioingenieriars@gmail.com",
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-08-07 22:43:28"
  },
  {
    name: "DR DAVID ZAMORA CONTRERAS ",
    contact: "7551308311",
    address: "MAR MUERTO #60 COLONIA  CENTRO, ZIHUATANEJO  GUERRERO , CP40890 ENTRE  MAR NEGRO Y MAR EGEO",
    map_url: "https://goo.gl/maps/Z6GFrMS8H5GYwy138",
    email: "cedizihua@gmail.com",
    optionalEmail: "cedizihua@gmail.com",
    company_name: "DAVID ZAMORA CONTRERAS",
    postalCode: "40890",
    rfc: "",
    status: "active",
    createdAt: "2023-08-08 22:57:31"
  },
  {
    name: "DR. ELEAZAR FIGUEROA PERALTA ",
    contact: "7271004186",
    address: "Buenavista de Cuellar, Guerrero",
    map_url: "https://goo.gl/maps/1E9uUbVi7xZcCgkn9",
    email: "figueroaeleazar826@gmail.com",
    optionalEmail: null,
    company_name: ".",
    postalCode: null,
    rfc: "",
    status: "active",
    createdAt: "2023-08-11 15:56:15"
  }
  ];

  for (const customer of customers) {
    const exists = await prisma.customer.findFirst({ where: { name: customer.name } });
    if (!exists) {
      await prisma.customer.create({
        data: {
          name: customer.name,
          contact: customer.contact,
          address: customer.address,
          map_url: customer.map_url,
          email: customer.email,
          optional_email: customer.optionalEmail, 
          company_name: customer.company_name,
          postal_code: customer.postalCode,
          rfc: customer.rfc,
          status: customer.status,
          created_at: new Date(customer.createdAt),
        },
      });
    }
  }

  console.log('Clientes insertados desde base antigua.');
}
